project:
  name: "TXTDirect Website"
  state: "stable"
  image: "https://github.com/txtdirect/website/blob/master/static/images/logo.svg"
  website: "https://about.txtdirect.org"
  oneLiner: "TXTDirect website"
  description: |
    TXTDirect website repository for the static website hosted at https://about.txtdirect.org.  
    Built with [Hugo](https://gohugo.io) and [Syna](https://syna.okkur.org).
  version: "v0.1.0"
  mainLicense: "CCByNcSa"

vision:
  type: "community"
  overview: |
    Community website to showcase TXTDirect.

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/txtdirect/website/labels/starter%20issue"

emails:
  security: "security@okkur.org"
  coc: "coc@okkur.org"

copyright:
  year: "2017"

cla:
  copyrightHolder: "nzt.ventures GmbH"
  mail: "legal@nzt.ventures"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/txtdirect/website/"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-stable-green.svg"
    alt: "state"
  - image: "https://img.shields.io/github/license/txtdirect/website.svg"
    link: "LICENSE"
    alt: "license"

reposeed:
  configVersion: "v1"
