# Site settings
baseurl = "https://about.txtdirect.org/"
languageCode = "en-us"
title = "TXTDirect - DNS TXT-record based redirects"
theme = "syna"
version = "0.3.0"
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

pygmentsCodeFences = true 
DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "DNS TXT-record based redirects"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"
    css = []
    js  = []

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.seetheprogress.com"
    id = "12"
    domain = "about.txtdirect.org" # Track subdomains via "*.example.com"

  [params.colors]
    gray600 = "#73718D"
    blue = "#0071bc"
    red = "#f44336"
    yellow = "#b58d39"
    green = "#389d71"
    cyan = "#293148"

[[menu.main]]
  url = "/docs/"
  name = "Docs"
  weight = 10

[[menu.main]]
  url = "/hosted"
  name = "Hosted Service"
  weight = 10

[[menu.copyright_footer]]
  url = "/imprint"
  name = "Imprint"
  weight = 10
