# Site settings
baseurl = "https://about.txtdirect.org/"
languageCode = "en-us"
title = "TXTDirect - DNS TXT-record based redirects"
theme = "syna"
version = "0.3.0"
enableGitInfo = true

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

pygmentsCodeFences = true 
DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "DNS TXT-record based redirects"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"
    css = ["css/overwrite.css"]
    js  = []

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.seetheprogress.com"
    id = "12"
    domain = "about.txtdirect.org" # Track subdomains via "*.example.com"

[[menu.main]]
  url = "#single-subdomain"
  name = "Hosted Service"
  weight = 10

[[menu.main]]
  url = "/gopkg"
  name = "Gopkg.link"
  weight = 20

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 30

[[menu.copyright_footer]]
  url = "/about"
  name = "About Us"
  weight = 10
