# Site settings
baseurl = "https://about.txtdirect.org/"
languageCode = "en-us"
title = "TXTDirect - DNS TXT-record based redirects"
theme = "syna"
version = "0.3.0"
enableGitInfo = true

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

pygmentsCodeFences = true 
DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "DNS TXT-record based redirects"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"
    css = []
    js  = []

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.seetheprogress.com"
    id = "12"
    domain = "about.txtdirect.org" # Track subdomains via "*.example.com"

  [params.colors]
    white = "#fff"
    gray100 = "#f8f9fa" # light
    gray200 = "#e9ecef"
    gray300 = "#dee2e6"
    gray400 = "#ced4da"
    gray500 = "#adb5bd"
    gray600 = "#868e96" # secondary
    gray700 = "#495057"
    gray800 = "#343a40" # dark
    gray900 = "#212529"
    black = "#000"
    blue = "#0071bc" # primary
    indigo = "#4b00bc"
    purple = "#a900bc"
    pink = "#e83e8c"
    red = "#bc0013" # danger
    orange = "#bc4b00"
    yellow = "#bca900" # warning
    green = "#13bc00" # success
    teal = "#00bca9"
    cyan = "#0affe6" # info

[[menu.main]]
  url = "/hosted"
  name = "Hosted Service"
  weight = 10

[[menu.main]]
  url = "/gopkg"
  name = "Gopkg.link"
  weight = 20

[[menu.copyright_footer]]
  url = "/imprint"
  name = "Imprint"
  weight = 10
